
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePDF = (result, fileName = 'Matchly_Report.pdf') => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;

    // Colors
    const colors = {
        primary: [249, 115, 22], // Orange #f97316
        secondary: [6, 182, 212], // Cyan #06b6d4
        dark: [30, 41, 59],     // Slate 900
        gray: [100, 116, 139],  // Slate 500
        light: [241, 245, 249], // Slate 100
        white: [255, 255, 255]
    };

    // Helper: Draw Header
    const drawHeader = () => {
        // Top Bar
        doc.setFillColor(...colors.dark);
        doc.rect(0, 0, pageWidth, 20, 'F');

        // Logo Text
        doc.setTextColor(...colors.white);
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("Matchly AI", margin, 13);

        // Tagline
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(200, 200, 200);
        doc.text("Advanced Resume Analysis", pageWidth - margin - 50, 13);
    };

    // Helper: Draw Footer
    const drawFooter = (pageNo) => {
        doc.setFillColor(...colors.light);
        doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');
        doc.setFontSize(8);
        doc.setTextColor(...colors.gray);
        doc.text(`Generated by Matchly AI • ${new Date().toLocaleDateString()}`, margin, pageHeight - 6);
        doc.text(`Page ${pageNo}`, pageWidth - margin - 10, pageHeight - 6);
    };

    // --- PAGE 1: SCORECARD & SUMMARY ---
    drawHeader();

    let y = 35;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(...colors.dark);
    doc.setFont("helvetica", "bold");
    doc.text("Candidate Analysis Report", margin, y);

    // Score Circle (Visual Representation)
    y += 15;
    const score = result.analysis.overall_score;
    const circleX = pageWidth - margin - 30;
    const circleY = y + 10;
    const radius = 25;

    // Draw Circle Background
    doc.setFillColor(...colors.light);
    doc.circle(circleX, circleY, radius, 'F');

    // Draw Arc (approximate for visual flair - jsPDF doesn't do strokes easily, use text)
    doc.setFontSize(30);
    doc.setTextColor(score > 70 ? colors.secondary[0] : score > 40 ? colors.primary[0] : [239, 68, 68][0],
        score > 70 ? colors.secondary[1] : score > 40 ? colors.primary[1] : [239, 68, 68][1],
        score > 70 ? colors.secondary[2] : score > 40 ? colors.primary[2] : [239, 68, 68][2]);
    doc.setFont("helvetica", "bold");
    doc.text(`${score}`, circleX - 10, circleY + 4);

    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text("MATCH SCORE", circleX - 12, circleY + 12);

    // Candidate/Job Info
    doc.setFontSize(12);
    doc.setTextColor(...colors.dark);
    doc.text(`Analysis ID: #${Math.floor(Math.random() * 10000)}`, margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(...colors.gray);
    doc.text("Assessment Date: " + new Date().toDateString(), margin, y);

    // Summary Section
    y += 35;
    doc.setFillColor(...colors.light);
    doc.roundedRect(margin, y, pageWidth - (margin * 2) - 70, 40, 3, 3, 'F');

    doc.setFontSize(11);
    doc.setTextColor(...colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE SUMMARY", margin + 5, y + 10);

    doc.setFontSize(10);
    doc.setTextColor(...colors.dark);
    doc.setFont("helvetica", "normal");
    const summaryText = doc.splitTextToSize(result.ai_insights.summary.replace(/<[^>]+>/g, ''), pageWidth - (margin * 2) - 80);
    doc.text(summaryText, margin + 5, y + 20);

    // --- Breakdown Table ---
    y += 50;

    const breakdownData = [
        ["Metric", "Value", "Max", "Status"],
        ["Skills Match", `${result.analysis.breakdown.skill_score}`, "40", result.analysis.breakdown.skill_score > 25 ? "Strong" : "Weak"],
        ["Experience", `${result.analysis.breakdown.experience_score}`, "20", result.analysis.breakdown.experience_score > 10 ? "Good" : "Low"],
        ["Credentials", `${result.analysis.breakdown.education_score}`, "10", "Verified"],
        ["Tech Stack", `${result.analysis.breakdown.bonus_score}`, "20", result.analysis.breakdown.bonus_score > 10 ? "Aligned" : "Gap"],
        ["ATS / Quality", `${result.analysis.breakdown.quality_score}`, "10", "Pass"]
    ];

    doc.autoTable({
        startY: y,
        head: [breakdownData[0]],
        body: breakdownData.slice(1),
        theme: 'grid',
        headStyles: { fillColor: colors.dark, textColor: colors.white },
        alternateRowStyles: { fillColor: colors.light },
        styles: { fontSize: 10, cellPadding: 5 }
    });

    y = doc.lastAutoTable.finalY + 15;

    // --- PAGE 2: DETAILED INSIGHTS ---
    // (Or continue if space permits)
    if (y > pageHeight - 60) {
        drawFooter(1);
        doc.addPage();
        drawHeader();
        y = 35;
    }

    // Strength & Weakness Lists
    doc.setFontSize(14);
    doc.setTextColor(...colors.secondary);
    doc.setFont("helvetica", "bold");
    doc.text("Key Strengths", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setTextColor(...colors.dark);
    doc.setFont("helvetica", "normal");
    result.ai_insights.strengths.forEach(str => {
        doc.text(`• ${str.replace(/<[^>]+>/g, '')}`, margin + 5, y);
        y += 6;
    });

    y += 10;
    doc.setFontSize(14);
    doc.setTextColor([239, 68, 68]); // Red
    doc.setFont("helvetica", "bold");
    doc.text("Critical Gaps", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setTextColor(...colors.dark);
    doc.setFont("helvetica", "normal");
    result.ai_insights.weaknesses.forEach(wk => {
        doc.text(`• ${wk.replace(/<[^>]+>/g, '')}`, margin + 5, y);
        y += 6;
    });

    // Missing Skills Grid
    y += 15;
    doc.setFontSize(14);
    doc.setTextColor(...colors.primary);
    doc.setFont("helvetica", "bold");
    doc.text("Missing Keywords (ATS)", margin, y);
    y += 8;

    const skills = result.analysis.missing_skills.join(", ");
    const skillLines = doc.splitTextToSize(skills, pageWidth - (margin * 2));
    doc.setFontSize(10);
    doc.setTextColor(...colors.gray);
    doc.setFont("helvetica", "italic");
    doc.text(skillLines, margin, y);
    y += (skillLines.length * 6) + 10;

    // Action Plan
    if (y > pageHeight - 50) {
        drawFooter(doc.internal.getNumberOfPages());
        doc.addPage();
        drawHeader();
        y = 35;
    }

    doc.setFillColor(...colors.light);
    doc.rect(margin, y, pageWidth - (margin * 2), 40, 'F');

    doc.setFontSize(12);
    doc.setTextColor(...colors.dark);
    doc.setFont("helvetica", "bold");
    doc.text("Recommended Action Plan", margin + 5, y + 10);

    y += 18;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    result.ai_insights.action_plan.forEach(action => {
        const actionText = `-> ${action.replace(/<[^>]+>/g, '')}`;
        const lines = doc.splitTextToSize(actionText, pageWidth - (margin * 2) - 10);
        doc.text(lines, margin + 5, y);
        y += (lines.length * 5) + 3;
    });

    // Final Footer
    drawFooter(doc.internal.getNumberOfPages());

    doc.save(fileName);
};
